# Generated by Django 5.1.2 on 2024-11-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('reviews_count', models.IntegerField()),
                ('is_promotion', models.BooleanField(default=False)),
                ('promotion_details', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
