# Generated by Django 5.1.2 on 2024-11-06 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_add_product', 'Can add product')]},
        ),
    ]
